openapi: "3.0.2"
info:
  title: API Ajmanre
  version: "1.0"
servers:
  - url: http://localhost:{port}
    description: The production API server
    variables:
      port:
        enum:
          - '8443'
          - '443'
        default: '8443'
tags:
  - name: Ajmanre
    description: Ajmanre.
paths:
  /auth/signin:
    post:
      tags:
        - "signin"
      summary: "signin"
      description: "signin"
      operationId: "signin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: "JWT response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JwtResponse"
        "405":
          description: "Invalid input"
  /auth/signup:
    post:
      tags:
        - "signup"
      summary: "signup"
      description: "signup"
      operationId: "signup"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        "200":
          description: "MessageResponse"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
        "405":
          description: "Invalid input"
  /prop/type:
    post:
      tags:
        - "propType"
      summary: "property type"
      operationId: "propType"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PropertyTypeRequest"
      responses:
        "200":
          description: "MessageResponse"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
        "405":
          description: "Invalid input"
  /prop/type/hierarchy:
    get:
      tags:
        - "propTypeHierarchy"
      summary: "property type hierarchy"
      operationId: "propTypeHierarchy"
      responses:
        "200":
          description: "property type hierarchy"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PropertyTypeHierarchy"
        "405":
          description: "Invalid input"
components:
  schemas:
    LoginRequest:
      type: "object"
      required:
        - username
        - password
      properties:
        username:
          type: "string"
          description: "Username"
        password:
          type: "string"
          description: "Password"
    JwtResponse:
      type: "object"
      properties:
        accessToken:
          type: "string"
          description: "token"
        type:
          type: "string"
          description: "type"
        id:
          type: "string"
          description: "id"
        username:
          type: "string"
          description: "Username"
        email:
          type: "string"
          description: "email"
        roles:
          type: "array"
          description: "roles"
          items:
            type: string
          example: ['admin', 'agent', 'user']
    SignupRequest:
      type: "object"
      required:
        - username
        - password
        - email
      properties:
        username:
          type: "string"
          description: "Username"
        password:
          type: "string"
          description: "Password"
        email:
          type: "string"
          description: "email"
        roles:
          type: "array"
          description: "roles"
          items:
            type: string
          example: ['admin', 'agent', 'user']
    MessageResponse:
      type: "object"
      required:
        - message
      properties:
        message:
          type: "string"
          description: "Message"
        identifier:
          type: "string"
          description: "If identifier has to be in response"
    PropertyTypeRequest:
      type: "object"
      required:
        - type
        - order
      properties:
        id:
          type: "string"
          description: "hierarchy id"
        type:
          type: "string"
          description: "type of the property"
        order:
          type: "integer"
          description: "order list on this value"
        child:
          $ref: "#/components/schemas/PropertyTypeChild"
    PropertyTypeChild:
      type: "object"
      required:
        - type
        - order
      properties:
        type:
          type: "string"
          description: "type of the property"
        order:
          type: "integer"
          description: "order list on this value"
        child:
          $ref: "#/components/schemas/PropertyTypeChild"
    PropertyType:
      type: "object"
      required:
        - id
        - enable
        - type
        - order
      properties:
        id:
          type: "string"
        enable:
          type: "boolean"
        type:
          type: "string"
          description: "type of the property"
        order:
          type: "integer"
          description: "order list on this value"
        child:
          $ref: "#/components/schemas/PropertyTypeChild"
    PropertyTypeHierarchy:
      type: "object"
      required:
        - type
        - order
      properties:
        id:
          type: "string"
          description: "id of hierarchy"
        type:
          type: "string"
          description: "type of the property"
        order:
          type: "integer"
          description: "order list on this value"
        children:
          type: "array"
          description: "property type hierarchy"
          items:
            $ref: "#/components/schemas/PropertyTypeItem"
    PropertyTypeItem:
      type: "object"
      required:
        - type
        - order
      properties:
        type:
          type: "string"
          description: "type of the property"
        order:
          type: "integer"
          description: "order list on this value"
        children:
          type: "array"
          description: "property type hierarchy"
          items:
            $ref: "#/components/schemas/PropertyTypeItem"